language: common-lisp
sudo: enabled
os:
  - linux
  - osx
dist: xenial
addons:
  homebrew:
    packages: sbcl
install: ./scripts/install-deps.sh
script: ./scripts/build.sh
before_deploy: ./scripts/create-dist.sh
deploy:
  provider: releases
  api_key:
    secure: J1kh7HgydJYsENltYiz4LHspQZU/Zd+zPsLfF3euf8aD1P7TVRH71F4qUqq1z3LYOfWTnYGO/GN7YJg+LBpfTYz/Z95qJwIZlha1c+KF/FVaqzz8ge5FznLVE72zhxv06hRk8+K8O0IDlKcZw8L27cTTvvoebC3IuU0mSsY1EtmsCzu6uPEnXl3aObS8dsN4CuNpz54rK7jtzo9T9hkQXnPLM2G7D4AlkqiwTHQGVMODKM/CPZdgkhGssWrRyt4eunK2LjQ4gxZBxjStXsTthF+6ZLDhHNT9+oqiFHardX8O4aRDYNsvceh0FoYK4rZyGEpE3HfhZqKTxV6AXTI6NFI6v6C8mMp74ZShUqyPh8zq5/rBuztMpbsbOLz8QK/SL0Yr2heZGQeprs71+C1Y6gKXppwNZdA0wmhYilGtXS5mwgkZRxMT/aTiZ8h8EMUiFKfPTi1U5zCfib4mSrPnJAuFkwHHZ77/ElIK0IV6U7DK9TLqPDBio/AdtX7R98Vpq7clLReYuqT045w5GWcJgQRH9QPRTmN0Y5J3let7ah4AuStrvqkLghFRL41vet2Lltsqu7sq6m5cyYxoEDF7RCY91mGy9qOE1cew1nznxJuABFO4x9/mEOkQ0ri0JxOcT9+C4XvRm/AzFjq/wxqZVhj5L/kPMPDHeC2cFVaaRZw=
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true
